### ISSUE TITLE
Bagaimana cara runnya?

### ISSUE THREAD

**Issue by fajarwahyu99** [yafithekid/web-crawler#1]
Bagaimana cara runnya?
Apakah ini pakai database?

**Comment by yafithekid** [comment]
Install visual studio IDE dan import project ini.

Project ini tidak pakai database

**Comment by fajarwahyu99** [comment]
gunanya buat apa ya ini? pakai metode apa?

Pada tanggal Sab, 30 Jun 2018 10.31, Muhammad Yafi <notifications@github.com>
menulis:
